service: aws-node-rest-api

frameworkVersion: '>=1.1.0 <2.0.0'

# custom:
#   babelPresets:
#     - latest

# plugins:
#   - serverless-babel-plugin

provider:
  name: aws
  runtime: nodejs12.x

functions:
  user:
    handler: api.handler
    events:
      - http:
          path: github
          method: get
          cors: true
